// Autogenerated JS file

var nodeTemplate = document.querySelector("#navNodeTemplate");
var leafTemplate = document.querySelector("#navLeafTemplate");

$.ajax("nav.json").done(function (navTree) {
  var navTreeRoot = JSON.parse(navTree);
  var $contentFrame = $("#contentFrame");
  var $leftNavContainer = $("#rootNavNode");

  navTreeRoot.children.forEach(function (navNode) {
    $leftNavContainer.append(renderNavNodeRecursive(navNode));
  })

});

function renderNavNodeRecursive(node) {
  if (node.isLeaf) {
    var $leaf = $(document.importNode(leafTemplate.content, true));
    var $titleLink = $leaf.find("[data-id='navItemTitle']");

    $titleLink.text(node.title);
    $titleLink.attr("href", node.url);

    return $leaf;
  } else {
    var $node = $(document.importNode(nodeTemplate.content, true));
    var $titleLink = $node.find("[data-id='navItemTitle']");
    var $children = $node.find("[data-id='navChildren']");

    $titleLink.text(node.title);
    $titleLink.attr("href", node.url);

    node.children.forEach(function (navNode) {
      $children.append(renderNavNodeRecursive(navNode));
    });

    return $node;
  }
}